# Generated by Django 4.2.7 on 2023-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_player_injured_res_list_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='injured_res_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
